### ISSUE TITLE
Documentation tutorial - fluid simulator based on qutip

### ISSUE THREAD

**Issue by imvetri** [qutip/qutip-doc#121]
Suggestion to add tutorial to build a fluid simulator based on quantum physics. It would a good exercise for learners.

**Comment by nathanshammah** [comment]
I am not sure what is the topic of interest here, i.e. what fluid simulator would be based on quantum physics. As far as I am aware, this kind of physical study is not within the reach or scope of QuTiP. In order to observe a fluid-like dynamics, one would need spatial description and viscosity. QuTiP's main machinery is focused on Hilbert (Liouvillian)-space formalism and Fock states. I don't see how this could be highlighted in the documentation as it is not something that I see easily happening in the dynamics. 

One could include dynamics of the Wigner function of a given dissipative system (such as a dissipative Dicke model) that show fluxes. 
In polaritons it is possible to observe fluid dynamics in experiments. Numerical tools usually do not use QuTiP for such descriptions. Especially in condensates, it is possible to investigate the threshold of the superfluid behavior, which involves nonlinear terms in the dynamical functions, e.g., the pseudopotential in the Gross-Pitaevskii equation. QuTiP tools do not include such dynamical equations, as far as I am aware.

**Comment by imvetri** [comment]
Here is a dancing droplet experiment and this behaviour of fluids opens up lot of possibilities to alternative models to artificial neural networks.

https://github.com/imvetri/artificial-intelligence/blob/master/dancinf.droplets.gif

I was hoping to simulate this behaviour of fluids based on quantum physics instead of conventional fluids model that tries to express in terms of viscosity. 


I initially thought it would be a great addition as a demo in this projects tool that's why brought this up.

**Comment by nathanshammah** [comment]
In that sense, the probability density of a wavefunction is an example of a fluid I guess.

The quantum counterpart I can imagine of is a wave function that gets into a multiple-square well 1D potential and where quantum tunneling allows it to go through barriers that are higher than its energy.
